model_provider: "google-gemini"  # Options: openai, groq, google-gemini

model_settings:
  openai:
    analysis_model: "gpt-4.1-2025-04-14"
    selenium_model: "gpt-4.1-2025-04-14"
    temperature: 0.2

  groq:
    analysis_model: "meta-llama/llama-4-scout-17b-16e-instruct"
    selenium_model: "meta-llama/llama-4-maverick-17b-128e-instruct"
    temperature: 0.2

  google-gemini:
    analysis_model: "gemini-2.5-flash" # High-speed structural HTML page analysis
    selenium_model: "gemini-2.5-pro"   # Complex reasoning for Selenium script generation
    temperature: 0.1